// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkrhteuadmlpckdjojrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrcmh0ZXVhZG1scGNrZGpvanJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDU4ODgsImV4cCI6MjA2NjYyMTg4OH0.lZvhNLuBp6_n1FE0DmtQ_4jD8wa9KFMpPl3-cujKV4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);